irssi: package libirc_proxy.a in PN-staticdev
* fixes:
  ERROR: irssi-1.0.4-r0 do_package_qa: QA Issue:
  non -staticdev package contains static .a library: irssi path '/work/core2-64-oe-linux/irssi/1.0.4-r0/packages-split/irssi/usr/lib/irssi/modules/libirc_proxy.a' [staticdev]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 8a84a0f802747798c7f35abc4b9e158ee3f30729)
Signed-off-by: Armin Kuster <akuster808@gmail.com>